[package]
name = "power_event_projector"
version = "0.1.0"
edition = "2021"

[dependencies]
dora-node-api = { workspace = true }
eyre = { workspace = true }
futures-util = "0.3"
mongodb = "2"
robo_rover_lib = { path = "../../robo_rover_lib" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.24.2", features = ["rt"] }
tracing = { workspace = true }
uuid = { workspace = true }
power_coordinator = { path = "../../common/power-coordinator" }
