#!/bin/bash
set -e

echo "==================================================================="
echo "  Robo-Fleet Rover-Kiwi Container Starting"
echo "==================================================================="

ROVER_ZENOH_CONNECT_ENDPOINT="${ROVER_ZENOH_CONNECT_ENDPOINT:-}"

# Verify hardware devices
echo "Checking for hardware devices..."
if [ ! -e "/dev/video0" ]; then
    echo "WARNING: /dev/video0 not found. Camera capture may fail."
    echo "  Make sure the container is running with --privileged or --device=/dev/video0"
else
    echo "✓ Camera device /dev/video0 found"
fi

if [ ! -d "/dev/snd" ]; then
    echo "WARNING: /dev/snd not found. Audio I/O may fail."
else
    echo "✓ Audio devices found in /dev/snd"
fi

# ---------------------------------------------------------------------------
# ALSA configuration — prefer host PulseAudio socket (same path as direct dora start);
# fall back to raw ALSA hardware if pulse socket is not mounted.
# ---------------------------------------------------------------------------
echo ""
echo "Configuring ALSA audio routing..."

# Check if host PulseAudio socket is available (mounted from docker-compose)
PULSE_SOCKET="${PULSE_SERVER#unix:}"
if [ -n "$PULSE_SERVER" ] && [ -S "$PULSE_SOCKET" ]; then
    echo "✓ Host PulseAudio socket found: $PULSE_SOCKET"
    pulse_runtime_dir="$(dirname "$(dirname "$PULSE_SOCKET")")"
    if [ -z "$XDG_RUNTIME_DIR" ] && [ -d "$pulse_runtime_dir" ]; then
        export XDG_RUNTIME_DIR="$pulse_runtime_dir"
        echo "✓ XDG_RUNTIME_DIR set from PulseAudio mount: $XDG_RUNTIME_DIR"
    fi
    cat > /etc/asound.conf <<EOF
# Auto-generated by entrypoint-rover.sh at container startup
# Routed through host PulseAudio — same audio path as direct dora start.
pcm.!default { type pulse }
ctl.!default { type pulse }
EOF
    echo "✓ ALSA configured: using host PulseAudio (pulse plugin)"
    # PULSE_SERVER is already exported from the container environment.
    # Preserve explicit AUDIO_DEVICE overrides such as "pulse".
    if [ -n "${AUDIO_DEVICE:-}" ]; then
        echo "✓ Preserving explicit AUDIO_DEVICE override: $AUDIO_DEVICE"
    fi
else
    echo "  PulseAudio socket not available — falling back to raw ALSA hardware"

    # Find the first USB capture device card name (e.g. "Camera" from PC-LM1E)
    # arecord -l format: "card N: ShortName [Long Name], device D: ..."
    USB_CAPTURE_CARD=$(arecord -l 2>/dev/null \
        | grep -E 'card [0-9]+:' \
        | grep -iv 'bcm\|hdmi\|vc4\|dummy\|loopback' \
        | sed 's/^.*card [0-9]*: \([^ ]*\).*/\1/' \
        | head -1)

    # Find the first non-HDMI playback card (skip vc4/HDMI — inaccessible in containers)
    PLAYBACK_CARD=$(aplay -l 2>/dev/null \
        | grep -E 'card [0-9]+:' \
        | grep -iv 'vc4\|hdmi\|bcm\|dummy' \
        | sed 's/^.*card \([0-9]*\):.*/\1/' \
        | head -1)

    if [ -n "$USB_CAPTURE_CARD" ]; then
        echo "✓ USB audio capture device: card '$USB_CAPTURE_CARD'"
        if [ -n "$PLAYBACK_CARD" ]; then
            echo "  Playback device: card '$PLAYBACK_CARD'"
        else
            echo "  No non-HDMI playback card found — audio_playback will degrade to silent mode"
        fi
        if [ -n "$PLAYBACK_CARD" ]; then
            cat > /etc/asound.conf <<EOF
# Auto-generated by entrypoint-rover.sh at container startup
# Capture  : USB mic  (card "$USB_CAPTURE_CARD")
# Playback : plughw:$PLAYBACK_CARD,0

pcm.usbmic {
    type plug
    slave.pcm "hw:CARD=$USB_CAPTURE_CARD,DEV=0"
}

ctl.usbmic {
    type hw
    card $USB_CAPTURE_CARD
}

pcm.!default {
    type asym
    playback.pcm {
        type plug
        slave.pcm "hw:$PLAYBACK_CARD,0"
    }
    capture.pcm {
        type plug
        slave.pcm "usbmic"
    }
}
EOF
        else
            cat > /etc/asound.conf <<EOF
# Auto-generated by entrypoint-rover.sh at container startup
# Capture  : USB mic  (card "$USB_CAPTURE_CARD")
# Playback : none (no non-HDMI card found — audio_playback will degrade to silent mode)

pcm.usbmic {
    type plug
    slave.pcm "hw:CARD=$USB_CAPTURE_CARD,DEV=0"
}

ctl.usbmic {
    type hw
    card $USB_CAPTURE_CARD
}

# Only configure capture on default; leave playback as system default
pcm.!default {
    type plug
    slave.pcm "usbmic"
}
EOF
        fi
        if [ -n "$PLAYBACK_CARD" ]; then
            echo "✓ ALSA configured: capture → $USB_CAPTURE_CARD, playback → plughw:$PLAYBACK_CARD,0"
        else
            echo "✓ ALSA configured: capture → $USB_CAPTURE_CARD (playback: none)"
        fi
        # Without an explicit override, prefer ALSA's configured 'default' PCM directly.
        # input_devices() enumeration can fail in containers (dsnoop IPC issues); letting
        # audio_capture fall back to default_input_device() respects asound.conf.
        if [ -z "${AUDIO_DEVICE:-}" ]; then
            unset AUDIO_DEVICE
        else
            echo "✓ Preserving explicit AUDIO_DEVICE override: $AUDIO_DEVICE"
        fi
    else
        echo "  No USB audio capture device found — audio capture will run in silent mode"
        if [ -n "$PLAYBACK_CARD" ]; then
            cat > /etc/asound.conf <<EOF
# Auto-generated by entrypoint-rover.sh at container startup
# No USB capture device; playback only via card $PLAYBACK_CARD.

pcm.!default {
    type plug
    slave.pcm "hw:$PLAYBACK_CARD,0"
}

ctl.!default {
    type hw
    card $PLAYBACK_CARD
}
EOF
            echo "✓ ALSA configured: playback → plughw:$PLAYBACK_CARD,0"
        else
            echo "  No non-HDMI playback card found either — leaving system ALSA defaults"
        fi
    fi  # end raw ALSA fallback
fi  # end pulse vs raw ALSA

# Verify models exist
echo ""
echo "Checking for required AI models..."
MODELS_OK=true

if [ ! -f "/models/yolo/yolo12n.onnx" ]; then
    echo "ERROR: YOLO model not found at /models/yolo/yolo12n.onnx"
    MODELS_OK=false
fi

if [ ! -f "/models/reid/osnet_x0_25.onnx" ]; then
    echo "ERROR: OSNet ReID model not found at /models/reid/osnet_x0_25.onnx"
    MODELS_OK=false
fi

SUPERTONIC_DIR="${EDGE_VOICE_MODEL_DIR:-/models/sherpa-onnx/tts/sherpa-onnx-supertonic-3-tts-int8-2026-05-11}"
if [ ! -f "$SUPERTONIC_DIR/duration_predictor.int8.onnx" ] || \
   [ ! -f "$SUPERTONIC_DIR/text_encoder.int8.onnx" ] || \
   [ ! -f "$SUPERTONIC_DIR/vector_estimator.int8.onnx" ] || \
   [ ! -f "$SUPERTONIC_DIR/vocoder.int8.onnx" ] || \
   [ ! -f "$SUPERTONIC_DIR/tts.json" ] || \
   [ ! -f "$SUPERTONIC_DIR/unicode_indexer.bin" ] || \
   [ ! -f "$SUPERTONIC_DIR/voice.bin" ]; then
    echo "WARNING: Supertonic TTS model incomplete at $SUPERTONIC_DIR"
    echo "  edge_voice will report an error state, but other nodes will continue"
else
    echo "✓ Supertonic TTS model found"
fi

if [ "$MODELS_OK" = false ]; then
    echo ""
    echo "Please ensure the models are downloaded and mounted correctly:"
    echo "  - Host: ./models/.cache/yolo/yolo12n.onnx"
    echo "  - Host: ./models/.cache/reid/osnet_x0_25.onnx"
    echo "  - Host: ${EDGE_VOICE_MODEL_DIR:-./models/.cache/sherpa-onnx/tts/sherpa-onnx-supertonic-3-tts-int8-2026-05-11/}"
    echo ""
    echo "To download and export models, run:"
    echo "  make models"
    exit 1
fi

echo "✓ YOLO model found"
echo "✓ OSNet ReID model found"

# Verify ONNX Runtime library
if [ ! -f "$ORT_DYLIB_PATH" ]; then
    echo "ERROR: ONNX Runtime library not found at $ORT_DYLIB_PATH"
    exit 1
fi
echo "✓ ONNX Runtime library found"

# Select dataflow based on ROVER_MODE
ROVER_MODE="${ROVER_MODE:-zenoh}"

if [ "$ROVER_MODE" = "direct" ]; then
    echo "Mode: DIRECT (web_bridge on :${SOCKET_IO_PORT:-3030}, no Zenoh)"
    DATAFLOW_SRC="/app/dataflow/rover-kiwi-direct-dataflow.yml"
    DATAFLOW_TMP="/tmp/rover-kiwi-direct-dataflow.yml"
else
    echo "Mode: ZENOH (zenoh-bridge, orchestra connection)"
    DATAFLOW_SRC="/app/dataflow/rover-kiwi-dataflow.yml"
    DATAFLOW_TMP="/tmp/rover-kiwi-dataflow.yml"
fi

if [ -n "$ROVER_ZENOH_CONNECT_ENDPOINT" ]; then
    tmp_zenoh_config="/tmp/rover-zenoh_config.json5"
    cp /app/config/zenoh_config.json5 "$tmp_zenoh_config"
    escaped_rover_zenoh_connect_endpoint="$(printf '%s\n' "$ROVER_ZENOH_CONNECT_ENDPOINT" | sed 's/[&\\]/\\&/g')"
    sed -i -E "s|\"tcp/[^\"]+\"|\"$escaped_rover_zenoh_connect_endpoint\"|" "$tmp_zenoh_config"
    export ROVER_ZENOH_CONFIG="$tmp_zenoh_config"
    echo "✓ Rover Zenoh connect endpoint override: $ROVER_ZENOH_CONNECT_ENDPOINT"
fi

# Create a modified dataflow YAML with updated paths
echo ""
echo "Updating dataflow YAML paths for container environment..."
cp "$DATAFLOW_SRC" "$DATAFLOW_TMP"

# Update binary paths from ../target/release/ to /app/bin/
sed -i 's|path: ../target/release/|path: /app/bin/|g' "$DATAFLOW_TMP"
sed -i 's|path: target/release/|path: /app/bin/|g' "$DATAFLOW_TMP"

# Update model paths from repo-local defaults to the mounted container paths.
sed -i 's|MODEL_PATH: "${ROVER_YOLO_MODEL_PATH:-models/.cache/yolo/yolo12n.onnx}"|MODEL_PATH: "/models/yolo/yolo12n.onnx"|g' "$DATAFLOW_TMP"
sed -i 's|REID_MODEL_PATH: "${ROVER_REID_MODEL_PATH:-models/.cache/reid/osnet_x0_25.onnx}"|REID_MODEL_PATH: "/models/reid/osnet_x0_25.onnx"|g' "$DATAFLOW_TMP"
escaped_supertonic_dir="$(printf '%s\n' "$SUPERTONIC_DIR" | sed 's/[&\\]/\\&/g')"
sed -i "s|EDGE_VOICE_MODEL_DIR: \"\${EDGE_VOICE_MODEL_DIR:-models/.cache/sherpa-onnx/tts/sherpa-onnx-supertonic-3-tts-int8-2026-05-11}\"|EDGE_VOICE_MODEL_DIR: \"$escaped_supertonic_dir\"|g" "$DATAFLOW_TMP"

if [ -n "${AUDIO_DEVICE:-}" ]; then
    escaped_audio_device="$(printf '%s\n' "$AUDIO_DEVICE" | sed 's/[&\\]/\\&/g')"
    sed -i -E "s|^([[:space:]]*)AUDIO_DEVICE:.*$|\\1AUDIO_DEVICE: \"$escaped_audio_device\"|g" "$DATAFLOW_TMP"
    echo "✓ Audio input device override: $AUDIO_DEVICE"
fi

# Update LD_LIBRARY_PATH
sed -i 's|LD_LIBRARY_PATH: "${HOME}/ws/robo-fleet-dora-rs/target/release"|LD_LIBRARY_PATH: "/usr/local/lib:/app/bin"|g' "$DATAFLOW_TMP"

# Update ARM_CONFIG path
sed -i 's|ARM_CONFIG: config/arm_6dof.toml|ARM_CONFIG: /app/config/rover/arm_6dof.toml|g' "$DATAFLOW_TMP"

echo "✓ Dataflow YAML updated"

# Display configuration
echo ""
echo "Configuration:"
echo "  - Mode: ${ROVER_MODE}"
echo "  - Entity ID: ${ENTITY_ID:-rover-kiwi}"
if [ "$ROVER_MODE" = "zenoh" ]; then
    echo "  - Zenoh Mode: ${ZENOH_MODE:-peer}"
else
    echo "  - Web UI Port: ${SOCKET_IO_PORT:-3030}"
fi
echo "  - Camera: ${SOURCE_TYPE:-webcam} (${SOURCE_URI:-/dev/video0})"
echo "  - YOLO Model: /models/yolo/yolo12n.onnx"
echo "  - ReID Model: /models/reid/osnet_x0_25.onnx"
echo "  - ONNX Runtime: $ORT_DYLIB_PATH"
echo ""

echo ""
echo "Starting Rover-Kiwi dataflow (mode: $ROVER_MODE)..."
echo "==================================================================="

exec dora run "$DATAFLOW_TMP"
