#!/bin/bash
set -e

echo "==================================================================="
echo "  Robo-Fleet Rover-Kiwi Container Starting"
echo "==================================================================="

# Verify hardware devices
echo "Checking for hardware devices..."
if [ ! -e "/dev/video0" ]; then
    echo "WARNING: /dev/video0 not found. Camera capture may fail."
    echo "  Make sure the container is running with --privileged or --device=/dev/video0"
else
    echo "✓ Camera device /dev/video0 found"
fi

if [ ! -d "/dev/snd" ]; then
    echo "WARNING: /dev/snd not found. Audio I/O may fail."
else
    echo "✓ Audio devices found in /dev/snd"
fi

# ---------------------------------------------------------------------------
# ALSA configuration — prefer host PulseAudio socket (same path as direct dora start);
# fall back to raw ALSA hardware if pulse socket is not mounted.
# ---------------------------------------------------------------------------
echo ""
echo "Configuring ALSA audio routing..."

# Check if host PulseAudio socket is available (mounted from docker-compose)
PULSE_SOCKET="${PULSE_SERVER#unix:}"
if [ -n "$PULSE_SERVER" ] && [ -S "$PULSE_SOCKET" ]; then
    echo "✓ Host PulseAudio socket found: $PULSE_SOCKET"
    cat > /etc/asound.conf <<EOF
# Auto-generated by entrypoint-rover.sh at container startup
# Routed through host PulseAudio — same audio path as direct dora start.
pcm.!default { type pulse }
ctl.!default { type pulse }
EOF
    echo "✓ ALSA configured: using host PulseAudio (pulse plugin)"
    # PULSE_SERVER is already exported from the container environment
    unset AUDIO_DEVICE
else
    echo "  PulseAudio socket not available — falling back to raw ALSA hardware"

    # Find the first USB capture device card name (e.g. "Camera" from PC-LM1E)
    # arecord -l format: "card N: ShortName [Long Name], device D: ..."
    USB_CAPTURE_CARD=$(arecord -l 2>/dev/null \
        | grep -E 'card [0-9]+:' \
        | grep -iv 'bcm\|hdmi\|vc4\|dummy\|loopback' \
        | sed 's/^.*card [0-9]*: \([^ ]*\).*/\1/' \
        | head -1)

    # Find the first non-HDMI playback card (skip vc4/HDMI — inaccessible in containers)
    PLAYBACK_CARD=$(aplay -l 2>/dev/null \
        | grep -E 'card [0-9]+:' \
        | grep -iv 'vc4\|hdmi\|bcm\|dummy' \
        | sed 's/^.*card \([0-9]*\):.*/\1/' \
        | head -1)

    if [ -n "$USB_CAPTURE_CARD" ]; then
        echo "✓ USB audio capture device: card '$USB_CAPTURE_CARD'"
        if [ -n "$PLAYBACK_CARD" ]; then
            echo "  Playback device: card '$PLAYBACK_CARD'"
        else
            echo "  No non-HDMI playback card found — audio_playback will degrade to silent mode"
        fi
        if [ -n "$PLAYBACK_CARD" ]; then
            cat > /etc/asound.conf <<EOF
# Auto-generated by entrypoint-rover.sh at container startup
# Capture  : USB mic  (card "$USB_CAPTURE_CARD")
# Playback : plughw:$PLAYBACK_CARD,0

pcm.usbmic {
    type plug
    slave.pcm "hw:CARD=$USB_CAPTURE_CARD,DEV=0"
}

ctl.usbmic {
    type hw
    card $USB_CAPTURE_CARD
}

pcm.!default {
    type asym
    playback.pcm {
        type plug
        slave.pcm "hw:$PLAYBACK_CARD,0"
    }
    capture.pcm {
        type plug
        slave.pcm "usbmic"
    }
}
EOF
        else
            cat > /etc/asound.conf <<EOF
# Auto-generated by entrypoint-rover.sh at container startup
# Capture  : USB mic  (card "$USB_CAPTURE_CARD")
# Playback : none (no non-HDMI card found — audio_playback will degrade to silent mode)

pcm.usbmic {
    type plug
    slave.pcm "hw:CARD=$USB_CAPTURE_CARD,DEV=0"
}

ctl.usbmic {
    type hw
    card $USB_CAPTURE_CARD
}

# Only configure capture on default; leave playback as system default
pcm.!default {
    type plug
    slave.pcm "usbmic"
}
EOF
        fi
        if [ -n "$PLAYBACK_CARD" ]; then
            echo "✓ ALSA configured: capture → $USB_CAPTURE_CARD, playback → plughw:$PLAYBACK_CARD,0"
        else
            echo "✓ ALSA configured: capture → $USB_CAPTURE_CARD (playback: none)"
        fi
        # Unset AUDIO_DEVICE so audio_capture uses ALSA's configured 'default' PCM directly.
        # input_devices() enumeration fails in containers (dsnoop IPC issues); default_input_device()
        # calls snd_pcm_open("default",...) which bypasses enumeration and respects asound.conf.
        unset AUDIO_DEVICE
    else
        echo "  No USB audio capture device found — audio capture will run in silent mode"
        if [ -n "$PLAYBACK_CARD" ]; then
            cat > /etc/asound.conf <<EOF
# Auto-generated by entrypoint-rover.sh at container startup
# No USB capture device; playback only via card $PLAYBACK_CARD.

pcm.!default {
    type plug
    slave.pcm "hw:$PLAYBACK_CARD,0"
}

ctl.!default {
    type hw
    card $PLAYBACK_CARD
}
EOF
            echo "✓ ALSA configured: playback → plughw:$PLAYBACK_CARD,0"
        else
            echo "  No non-HDMI playback card found either — leaving system ALSA defaults"
        fi
    fi  # end raw ALSA fallback
fi  # end pulse vs raw ALSA

# Verify models exist
echo ""
echo "Checking for required AI models..."
MODELS_OK=true

if [ ! -f "/models/yolo/yolo12n.onnx" ]; then
    echo "ERROR: YOLO model not found at /models/yolo/yolo12n.onnx"
    MODELS_OK=false
fi

if [ ! -f "/models/reid/osnet_x0_25.onnx" ]; then
    echo "ERROR: OSNet ReID model not found at /models/reid/osnet_x0_25.onnx"
    MODELS_OK=false
fi

if [ ! -d "/models/sherpa-onnx/vits-piper-en_US-lessac-medium" ]; then
    echo "WARNING: Sherpa-ONNX TTS model not found at /models/sherpa-onnx/vits-piper-en_US-lessac-medium"
    echo "  TTS functionality will not work, but other nodes will continue"
else
    echo "✓ Sherpa-ONNX TTS model found"
fi

if [ "$MODELS_OK" = false ]; then
    echo ""
    echo "Please ensure the models are downloaded and mounted correctly:"
    echo "  - Host: ./models/.cache/yolo/yolo12n.onnx"
    echo "  - Host: ./models/.cache/reid/osnet_x0_25.onnx"
    echo "  - Host: ./models/.cache/sherpa-onnx/vits-piper-en_US-lessac-medium/"
    echo ""
    echo "To download and export models, run:"
    echo "  make models"
    echo "  or"
    echo "  ./docker/scripts/download-models.sh"
    echo "  cd models/scripts && ./download_osnet_model.sh"
    echo "  cd models/scripts && python3 export_yolo_to_onnx.py"
    exit 1
fi

echo "✓ YOLO model found"
echo "✓ OSNet ReID model found"

# Verify ONNX Runtime library
if [ ! -f "$ORT_DYLIB_PATH" ]; then
    echo "ERROR: ONNX Runtime library not found at $ORT_DYLIB_PATH"
    exit 1
fi
echo "✓ ONNX Runtime library found"

# Select dataflow based on ROVER_MODE
ROVER_MODE="${ROVER_MODE:-zenoh}"

if [ "$ROVER_MODE" = "direct" ]; then
    echo "Mode: DIRECT (web_bridge on :${SOCKET_IO_PORT:-3030}, no Zenoh)"
    DATAFLOW_SRC="/app/dataflow/rover-kiwi-direct-dataflow.yml"
    DATAFLOW_TMP="/tmp/rover-kiwi-direct-dataflow.yml"
else
    echo "Mode: ZENOH (zenoh-bridge, orchestra connection)"
    DATAFLOW_SRC="/app/dataflow/rover-kiwi-dataflow.yml"
    DATAFLOW_TMP="/tmp/rover-kiwi-dataflow.yml"
fi

# Create a modified dataflow YAML with updated paths
echo ""
echo "Updating dataflow YAML paths for container environment..."
cp "$DATAFLOW_SRC" "$DATAFLOW_TMP"

# Update binary paths from ../target/release/ to /app/bin/
sed -i 's|path: ../target/release/|path: /app/bin/|g' "$DATAFLOW_TMP"
sed -i 's|path: target/release/|path: /app/bin/|g' "$DATAFLOW_TMP"

# Update model paths from ${HOME}/.cache/ to /models/
sed -i 's|MODEL_PATH: "${HOME}/.cache/yolo/yolo12n.onnx"|MODEL_PATH: "/models/yolo/yolo12n.onnx"|g' "$DATAFLOW_TMP"
sed -i 's|REID_MODEL_PATH: "${HOME}/.cache/reid/osnet_x0_25.onnx"|REID_MODEL_PATH: "/models/reid/osnet_x0_25.onnx"|g' "$DATAFLOW_TMP"
sed -i 's|TTS_MODEL_DIR: "${HOME}/.cache/sherpa-onnx/vits-piper-en_US-lessac-medium"|TTS_MODEL_DIR: "/models/sherpa-onnx/vits-piper-en_US-lessac-medium"|g' "$DATAFLOW_TMP"

# Update LD_LIBRARY_PATH
sed -i 's|LD_LIBRARY_PATH: "${HOME}/ws/robo-fleet-dora-rs/target/release"|LD_LIBRARY_PATH: "/usr/local/lib:/app/bin"|g' "$DATAFLOW_TMP"

# Update ARM_CONFIG path
sed -i 's|ARM_CONFIG: config/arm_6dof.toml|ARM_CONFIG: /app/config/rover/arm_6dof.toml|g' "$DATAFLOW_TMP"

echo "✓ Dataflow YAML updated"

# Display configuration
echo ""
echo "Configuration:"
echo "  - Mode: ${ROVER_MODE}"
echo "  - Entity ID: ${ENTITY_ID:-rover-kiwi}"
if [ "$ROVER_MODE" = "zenoh" ]; then
    echo "  - Zenoh Mode: ${ZENOH_MODE:-peer}"
else
    echo "  - Web UI Port: ${SOCKET_IO_PORT:-3030}"
fi
echo "  - Camera: ${SOURCE_TYPE:-webcam} (${SOURCE_URI:-/dev/video0})"
echo "  - YOLO Model: /models/yolo/yolo12n.onnx"
echo "  - ReID Model: /models/reid/osnet_x0_25.onnx"
echo "  - ONNX Runtime: $ORT_DYLIB_PATH"
echo ""

echo ""
echo "Starting Rover-Kiwi dataflow (mode: $ROVER_MODE)..."
echo "==================================================================="

exec dora run "$DATAFLOW_TMP"
