[package]
name = "resource_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
dora-node-api = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
robo_rover_lib = { path = "../../robo_rover_lib" }
sysinfo = "0.31"
chrono = "0.4"
