[package]
name = "reid_extractor"
version = "0.1.0"
edition = "2021"

[lib]
name = "reid_extractor"
path = "src/lib.rs"

[dependencies]
robo_rover_lib = { path = "../../robo_rover_lib" }
eyre = "0.6.12"
image = "0.25"
ndarray = "0.15"
ort = { version = "1.16.3", default-features = false, features = ["load-dynamic", "download-binaries"] }
tracing = "0.1"
