[package]
name = "audio_playback"
version = "0.1.0"
edition = "2021"

[dependencies]
dora-node-api = { workspace = true }
eyre = { workspace = true }
robo_rover_lib = { path = "../../robo_rover_lib" }
tracing = { workspace = true }
cpal = "0.15"
crossbeam-queue = "0.3"
rubato = { version = "=3.0.0", default-features = false }
serde_json = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
serde_yaml = "0.9"
